name: Auto Assign Reviewers

on:
  pull_request_target:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          addReviewers: true
          addAssignees: author

          reviewers: |
            GREEN
            RED
            BLUE
            YELLOW

          numberOfReviewers: 3
          numberOfAssignees: 1

          skipKeywords: |
            wip
            WIP
